# Generated by Django 4.2.7 on 2023-11-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='tags')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.session')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='wines')),
                ('order', models.IntegerField()),
                ('variety', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('alcohol_content', models.FloatField()),
                ('sweetness', models.FloatField()),
                ('tags', models.ManyToManyField(to='polls.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WineScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('user_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userscore')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.wine')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='wines',
            field=models.ManyToManyField(to='polls.wine'),
        ),
    ]
