# Generated by Django 4.2.7 on 2023-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_winescore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='tags',
            field=models.ManyToManyField(null=True, to='polls.tag'),
        ),
    ]
