# Generated by Django 4.2.7 on 2023-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_wine_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='wines',
            field=models.ManyToManyField(blank=True, to='polls.wine'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.tag'),
        ),
    ]
