# Generated by Django 4.2.7 on 2023-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_session_wines_alter_wine_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='emoji_sucre',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
