# Generated by Django 4.2.7 on 2023-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_wine_emoji_sucre'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wine',
            name='emoji_sucre',
            field=models.BooleanField(default=False),
        ),
    ]
