# Generated by Django 4.2.7 on 2023-11-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_wine_price_alter_wine_emoji_sucre'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='color',
            field=models.CharField(default='dsdsd', max_length=100),
            preserve_default=False,
        ),
    ]
