# Generated by Django 4.2.7 on 2024-07-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_wine_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='wines',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='order',
        ),
        migrations.CreateModel(
            name='SessionWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.session')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.wine')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'wine')},
            },
        ),
        migrations.AddField(
            model_name='winescore',
            name='session_wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.sessionwine'),
        ),
    ]
