# Generated by Django 4.2.7 on 2024-11-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wine',
            name='short_name',
            field=models.CharField(max_length=255),
        ),
    ]
